#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'nginx', '~> 2.7.4'

cookbook 'openssl', '~> 2.0.0'

cookbook 'php-fpm', '~> 0.6.10'

cookbook 'redis2', '~> 0.5.1'

#cookbook 'php-redis', '~> 0.1.1'

cookbook 'composer', '~> 1.0.5'

cookbook 'nodejs', '~> 2.1.0'